version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

# Options for custom base configuration file
clash_rule_base = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/base/all_base.tpl"
#surge_rule_base = "base/surge.conf"
#surfboard_rule_base = "base/surfboard.conf"
#mellow_rule_base = "base/mellow.conf"
#quan_rule_base = "base/quan.conf"
#quanx_rule_base = "base/quanx.conf"
#loon_rule_base = "base/loon.conf"
#sssub_rule_base = "base/shadowsocks_base.json"
#singbox_rule_base = "base/singbox.json"

# Options for adding emojis
add_emoji = false
remove_old_emoji = false

# Options for filtering nodes
#include_remarks = []
exclude_remarks = ["(到期|剩余流量|时间|官网|产品|重置|邀请)"]

[[rename]]
match = '\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?'
replace = "$1x"

[[custom_groups]]
import = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/snippets/groups.toml"

[[rulesets]]
import = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/snippets/rulesets_online.toml"

# [[template_args]]
# key = "clash.dns.port"
# value = "5353"